# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('comment', models.TextField(verbose_name='comment')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Published date')),
                ('is_spam', models.BooleanField(default=False, editable=False, verbose_name='spam?')),
                ('sentiment', models.SmallIntegerField(choices=[(-1, 'negative'), (0, 'neutral'), (1, 'positive')], default=0, verbose_name='Sentiment?')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
