# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_spam',
        ),
        migrations.AddField(
            model_name='comment',
            name='stats',
            field=models.TextField(default='', verbose_name='text statistics'),
            preserve_default=False,
        ),
    ]
